export interface GroupAdminPluginOptions {
  minimumAllowedLevel?: number;
  rejectionReason?: string;
  manualRejectionReason?: string;
  reviewerUserIds?: number[];
  moderatorUserIds?: number[];
  groupFileClassificationEnabled?: boolean;
  groupFileClassificationMode?: 'extension' | 'category';
  groupFileClassificationCron?: string;
  groupFileClassificationCategories?: Record<string, string[]>;
  groupFileClassificationFallbackFolderName?: string;
  groupMemberCardManagementEnabled?: boolean;
  groupMemberCardRuleScope?: 'global' | 'group';
  groupMemberCardPattern?: string;
  groupMemberCardGroupPatterns?: Record<string, string>;
  groupMemberCardViolationAction?: 'notify' | 'reset';
  groupMemberCardCheckCron?: string;
  inactiveCleanupCron?: string;
  inactiveCleanupFreeSlotsThreshold?: number;
  inactiveCleanupKickLimit?: number;
  spamDetectionWindowMs?: number;
  spamDetectionSegmentLimit?: number;
  spamAction?: 'kick' | 'mute';
  spamMuteDurationSeconds?: number;
  manualMuteDurationSeconds?: number;
  forbiddenWords?: string[];
  forbiddenWordMuteDurationSeconds?: number;
  blacklistUserIds?: number[];
  blacklistRejectionReason?: string;
  blacklistCleanupCron?: string;
  whitelistUserIds?: number[];
}
